ALTER TABLE "UserMedia" RENAME COLUMN "url" TO "mediaUrl";
ALTER TABLE "UserMedia" ADD COLUMN "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "UserMedia" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
